name: release

on:
  push:
    tags:
      - 'Bark空回通知'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          name: Bark空回通知
          tag_name: Bark空回通知
          files: |
            Bark空回通知.json
